### ISSUE TITLE
TileEntity_DeconRad error and an attempt to give a null achievement, starts spamming and clogs the entire server log

### ISSUE THREAD

**Issue by KaxelOleg** [TheOriginalGolem/Hbm-s-Nuclear-Tech-GIT#69]
1) 
[23:47:58] [Server thread/ERROR] [FML]: A TileEntity hbm:tileentity_deconrad(com.hbm.tileentity.machine.TileEntityDeconRad) has thrown an exception during loading, its state cannot be restored. Report this to the mod author
java.lang.InstantiationException: com.hbm.tileentity.machine.TileEntityDeconRad
        at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_351]
        at net.minecraft.tileentity.TileEntity.create(TileEntity.java:105) [avj.class:?]
        at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:495) [aye.class:?]
        at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:101) [ChunkIOProvider.class:?]
        at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:94) [ChunkIOExecutor.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:118) [on.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:89) [on.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.provideChunk(ChunkProviderServer.java:135) [on.class:?]
        at net.minecraft.world.World.getChunk(World.java:310) [amu.class:?]
        at net.minecraft.entity.Entity.setPositionAndRotation(Entity.java:1400) [vg.class:?]
        at net.minecraft.network.NetHandlerPlayServer.setPlayerLocation(NetHandlerPlayServer.java:626) [pa.class:?]
        at net.minecraft.network.NetHandlerPlayServer.setPlayerLocation(NetHandlerPlayServer.java:598) [pa.class:?]
        at journeymap.common.feature.JourneyMapTeleport.teleportEntity(JourneyMapTeleport.java:147) [JourneyMapTeleport.class:1.12.2-5.7.1]
        at journeymap.common.feature.JourneyMapTeleport.attemptTeleport(JourneyMapTeleport.java:83) [JourneyMapTeleport.class:1.12.2-5.7.1]
        at journeymap.common.command.CommandJTP.execute(CommandJTP.java:58) [CommandJTP.class:1.12.2-5.7.1]
        at com.feed_the_beast.ftbutilities.ranks.CommandOverride.execute(CommandOverride.java:83) [CommandOverride.class:?]
        at net.minecraft.command.CommandHandler.tryExecute(CommandHandler.java:119) [bj.class:?]
        at net.minecraft.command.CommandHandler.executeCommand(CommandHandler.java:91) [bj.class:?]
        at net.minecraft.network.NetHandlerPlayServer.handleSlashCommand(NetHandlerPlayServer.java:962) [pa.class:?]
        at net.minecraft.network.NetHandlerPlayServer.processChatMessage(NetHandlerPlayServer.java:941) [pa.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.processPacket(SourceFile:37) [la.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.processPacket(SourceFile:9) [la.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_351]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_351]
        at net.minecraft.util.Util.runTask(SourceFile:529) [h.class:?]
        at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:723) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_351]
Caused by: java.lang.NoSuchMethodException: com.hbm.tileentity.machine.TileEntityDeconRad.<init>()
        at java.lang.Class.getConstructor0(Unknown Source) ~[?:1.8.0_351]
        ... 31 more
This happened, as I understood it, when we either broke some radioactive blocks, or raised them
2) [hbm]: Failed to grant null advancement! This should never happen.
This happens when you get a lot of radiation. It is possible that it is related to the fact that we transferred roughly all the data from one world to another, including the achievements folder from the world folder and other folders.

**Comment by TheOriginalGolem** [comment]
Tf, thought I fixed that, will look into it

**Comment by jone87** [comment]
I have the same problem plz my server is crashing bc of this :(

**Comment by TheOriginalGolem** [comment]
This is no longer maintained, please use ntm community edition instead

**Comment by jone87** [comment]
> Tf, thought I fixed that, will look into it
But i cant change the mod, i have the world over 2 years, i cant build all that stuff :(
