### ISSUE TITLE
Large glowing green mushrooms overwrite all blocks in their way when grown, causing crashes.

### ISSUE THREAD

**Issue by KauaiMoho** [TheOriginalGolem/Hbm-s-Nuclear-Tech-GIT#76]
Bonemealing large glowing green mushrooms with blocks in the way of their generation will cause those blocks to be deleted. With certain modded tile Entities getting deleted, it can crash the server. I feel like the intended behavior should be to ignore all foreign blocks in the way when grown, rather than having those blocks overwritten.

**Comment by TheOriginalGolem** [comment]
Firstly, whatever mod that doesnt have basic error checking for their tile entities is just made badly. On the issue itself, I'll see what I can do.

**Comment by KauaiMoho** [comment]
There also seems to be a crash associated with vanilla tileEntities when mushrooms grow, as dispensers filled with bonemeal growing the mushrooms being overwritten also crashed the game.

**Comment by Vetpetmon** [comment]
Any crashlogs? Crashlogs would help us out the most, it'll tell us exactly where and what in the code went wrong.

**Comment by KauaiMoho** [comment]
here ya go. I am running some other mods, but they shouldn't be affecting anything.
[crash-2023-01-28_22.01.46-server.txt](https://github.com/TheOriginalGolem/Hbm-s-Nuclear-Tech-GIT/files/10529148/crash-2023-01-28_22.01.46-server.txt)

**Comment by KauaiMoho** [comment]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  TransformerLoader (OpenComputers-MC1.12.2-1.7.7+5413028.jar)
  GSHooksLoader (GalaxySpace-1.12.2-2.0.19.jar)
  MicdoodlePlugin (Galacticraft-1.12.2-4.0.4.jar)
Contact their authors BEFORE contacting forge

// You should try our sister game, Minceraft!

Time: 1/28/23 10:01 PM
Description: Exception while ticking a block

java.lang.IllegalArgumentException: Cannot get property PropertyDirection{name=facing, clazz=class net.minecraft.util.EnumFacing, values=[down, up, north, south, west, east]} as it does not exist in BlockStateContainer{block=hbm:mush_block, properties=[]}
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:201)
	at net.minecraft.dispenser.BehaviorDefaultDispenseItem.func_82482_a(SourceFile:15)
	at net.minecraft.block.BlockDispenser.func_176439_d(SourceFile:119)
	at net.minecraft.block.BlockDispenser.func_180650_b(SourceFile:143)
	at net.minecraft.world.WorldServer.func_72955_a(WorldServer.java:737)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:223)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:201)
	at net.minecraft.dispenser.BehaviorDefaultDispenseItem.func_82482_a(SourceFile:15)
	at net.minecraft.block.BlockDispenser.func_176439_d(SourceFile:119)
	at net.minecraft.block.BlockDispenser.func_180650_b(SourceFile:143)

-- Block being ticked --
Details:
	Block: minecraft:dispenser[facing=west,triggered=true]
	Block location: World: (80,72,236), Chunk: (at 0,4,12 in 5,14; contains blocks 80,0,224 to 95,255,239), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
Stacktrace:
	at net.minecraft.world.WorldServer.func_72955_a(WorldServer.java:737)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:223)

-- Affected level --
Details:
	Level name: temp
	All players: 1 total; [GCEntityPlayerMP['6litchh'/289, l='temp', x=79.84, y=71.51, z=233.03]]
	Chunk stats: ServerChunkCache: 658 Drop: 0
	Level seed: -994968248620785755
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (21,64,252), Chunk: (at 5,4,12 in 1,15; contains blocks 16,0,240 to 31,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 16941 game time, 16941 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 19528 (now: false), thunder time: 154750 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 752582880 bytes (717 MB) / 2524971008 bytes (2408 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2859 28 mods loaded, 28 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                  | Version        | Source                                         | Signature                                |
	|:------ |:------------------- |:-------------- |:---------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft           | 1.12.2         | minecraft.jar                                  | None                                     |
	| LCHIJA | mcp                 | 9.42           | minecraft.jar                                  | None                                     |
	| LCHIJA | FML                 | 8.0.99.99      | forge-1.12.2-14.23.5.2859.jar                  | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge               | 14.23.5.2859   | forge-1.12.2-14.23.5.2859.jar                  | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | micdoodlecore       | 4.0.4          | minecraft.jar                                  | None                                     |
	| LCHIJA | opencomputers|core  | 1.7.7+5413028  | minecraft.jar                                  | None                                     |
	| LCHIJA | galacticraftcore    | 4.0.4          | Galacticraft-1.12.2-4.0.4.jar                  | None                                     |
	| LCHIJA | galacticraftplanets | 4.0.4          | Galacticraft-1.12.2-4.0.4.jar                  | None                                     |
	| LCHIJA | asmodeuscore        | 0.0.30         | AsmodeusCore-1.12.2-0.0.31.jar                 | None                                     |
	| LCHIJA | codechickenlib      | 3.2.3.358      | CodeChickenLib-1.12.2-3.2.3.358-universal.jar  | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | redstoneflux        | 2.1.1          | RedstoneFlux-1.12-2.1.1.1-universal.jar        | None                                     |
	| LCHIJA | cofhcore            | 4.6.6          | CoFHCore-1.12.2-4.6.6.1-universal.jar          | None                                     |
	| LCHIJA | cofhworld           | 1.4.0          | CoFHWorld-1.12.2-1.4.0.1-universal.jar         | None                                     |
	| LCHIJA | crafttweaker        | 4.1.20         | CraftTweaker2-1.12-4.1.20.682.jar              | None                                     |
	| LCHIJA | ctgui               | 1.0.0          | CraftTweaker2-1.12-4.1.20.682.jar              | None                                     |
	| LCHIJA | jei                 | 4.16.1.301     | jei_1.12.2-4.16.1.301.jar                      | None                                     |
	| LCHIJA | crafttweakerjei     | 2.0.3          | CraftTweaker2-1.12-4.1.20.682.jar              | None                                     |
	| LCHIJA | galaxyspace         | 2.0.19         | GalaxySpace-1.12.2-2.0.19.jar                  | None                                     |
	| LCHIJA | hbm                 | hbm-1.8.2a-Gv2 | hbm-1.8.2a-Gv2.jar                             | None                                     |
	| LCHIJA | waila               | 1.8.26         | Hwyla-1.8.26-B41_1.12.2.jar                    | None                                     |
	| LCHIJA | literally_drugs     | 1.0.0          | Litterally+Drugs+0.2.jar                       | None                                     |
	| LCHIJA | opencomputers       | 1.7.7+5413028  | OpenComputers-MC1.12.2-1.7.7+5413028.jar       | None                                     |
	| LCHIJA | refinedstorage      | 1.6.16         | refinedstorage-1.6.16.jar                      | 57893d5b90a7336e8c63fe1c1e1ce472c3d59578 |
	| LCHIJA | thermalfoundation   | 2.6.7          | ThermalFoundation-1.12.2-2.6.7.1-universal.jar | None                                     |
	| LCHIJA | thermalexpansion    | 5.5.7          | ThermalExpansion-1.12.2-5.5.7.1-universal.jar  | None                                     |
	| LCHIJA | thermaldynamics     | 2.5.6          | ThermalDynamics-1.12.2-2.5.6.1-universal.jar   | None                                     |
	| LCHIJA | worldedit           | 6.1.10         | worldedit-forge-mc1.12.2-6.1.10-dist.jar       | None                                     |
	| LCHIJA | jade                | 0.1.0          | Jade-0.1.0.jar                                 | None                                     |

	Loaded coremods (and transformers): 
TransformerLoader (OpenComputers-MC1.12.2-1.7.7+5413028.jar)
  li.cil.oc.common.asm.ClassTransformer
GSHooksLoader (GalaxySpace-1.12.2-2.0.19.jar)
  galaxyspace.core.hooklib.minecraft.PrimaryClassTransformer
MicdoodlePlugin (Galacticraft-1.12.2-4.0.4.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [GCEntityPlayerMP['6litchh'/289, l='temp', x=79.84, y=71.51, z=233.03]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by Vetpetmon** [comment]
It IS a blockProperty casting issue. 

```
java.lang.IllegalArgumentException: Cannot get property PropertyDirection{name=facing, clazz=class net.minecraft.util.EnumFacing, values=[down, up, north, south, west, east]} as it does not exist in BlockStateContainer{block=hbm:mush_block, properties=[]}
```
`hbm:mush_block` has **no properties**, but whatever block it is trying to override, it's trying to carry over the previous blockstate, which has the `EnumFacing` values.

PS: `minecraft:dispenser`, a vanilla block, has these block properties, but `hbm:mush_block` does not. it's essentially a null variable error.

**Comment by Vetpetmon** [comment]
Because of the nature of this issue, it should be tested with log blocks, HBM tile entities, and so forth.

Give us results on various blocks, and see what errors and what doesn't.
